# 变量必须全部是大写字母

# Flask内置变量
DEBUG = True

# cookie
SET_COOKIE_PATH = '/'
SET_COOKIE_DOMAIN = None
SET_COOKIE_SECURE = False
SET_COOKIE_HTTPONLY = True
SET_COOKIE_SAMESITE = 'Strict'
SET_COOKIE_SESSION_TIME = None
SET_COOKIE_UNAVAILABLE = 0
SET_COOKIE_SIX_DAYS = 60*60*24*6